FROM python:3.8
MAINTAINER Victor<896370742@qq.com>

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --upgrade -i https://pypi.douban.com/simple/ pip 
RUN pip install  -i https://pypi.douban.com/simple/ -r requirements.txt
COPY . .

ENV PYTHONUNBUFFERED 1

EXPOSE 80
CMD ["python","manage.py","runserver","0:80"] 